In [16]:
from shopping import *
import numpy as np
evidence, labels = load_data(sys.argv[1])
X_train, X_test, y_train, y_test = train_test_split(
    evidence, labels, test_size=TEST_SIZE
)

# Train model and make predictions
model = train_model(X_train, y_train)
predictions = model.predict(X_test)

In [25]:
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [4]:
y_test

[1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [15]:
(y_test == predictions).sum()

4069

In [12]:
type(predictions)

numpy.ndarray

In [14]:
len(y_test)

4932

In [18]:
ones = np.ones(4932, dtype=int)
ones

array([1, 1, 1, ..., 1, 1, 1])

In [19]:
zeros=np.zeros(4932, dtype=int)
zeros

array([0, 0, 0, ..., 0, 0, 0])

In [30]:
all_actual_0 = (y_test == zeros).sum()

In [29]:
all_actual_1 = (y_test == ones).sum()

In [27]:
count_true_predict_1 = 0
count_true_predict_0 = 0

for actual, predict in zip(y_test, predictions):
    if actual == predict:
        if predict == 0:
            count_true_predict_0 += 1
        else:
            count_true_predict_1 += 1
print('true 0: ', count_true_predict_0, 'true 1: ', count_true_predict_1)

true 0:  3804 true 1:  304


In [33]:
sensitivity = count_true_predict_1/all_actual_1
sensitivity

0.4

In [34]:
specificity = count_true_predict_0/all_actual_0
specificity

0.9117929050814957